package supply_chain.slsa

# Software Supply Chain Security — SLSA Framework Governance
#
# Implements SLSA (Supply chain Levels for Software Artifacts) v1.0 verification
# and broader supply chain integrity controls.
#
# SLSA Levels:
#   Level 1 — Provenance exists, scripted build
#   Level 2 — Version-controlled, service-generated provenance
#   Level 3 — Hardened build platform, non-falsifiable provenance
#
# Also covers: SBOM completeness, dependency hygiene, license compliance,
# artifact signing (Sigstore/Cosign), and CVE policy enforcement.
#
# OPA endpoint: POST http://192.168.4.62:8182/v1/data/supply_chain/slsa
# Input: artifact metadata, provenance attestation, SBOM, build environment facts

import rego.v1

default compliant := false

compliant if { count(violations) == 0 }

# =============================================================================
# SLSA LEVEL ASSESSMENT
# =============================================================================

# Minimum SLSA level required (configurable per environment)
required_slsa_level := input.policy.required_slsa_level if {
	input.policy.required_slsa_level
} else := 2

slsa_level_1_met if {
	input.provenance.exists
	input.build.scripted
}

slsa_level_2_met if {
	slsa_level_1_met
	input.build.service_generated_provenance
	input.source.version_controlled
	input.build.build_service_used
}

slsa_level_3_met if {
	slsa_level_2_met
	input.build.hardened_platform
	input.build.non_falsifiable_provenance
	input.source.verified_history
	input.build.isolated_environment
}

current_slsa_level := 3 if { slsa_level_3_met }
current_slsa_level := 2 if { slsa_level_2_met; not slsa_level_3_met }
current_slsa_level := 1 if { slsa_level_1_met; not slsa_level_2_met }
current_slsa_level := 0 if { not slsa_level_1_met }

violations contains "SLSA: Build provenance attestation is missing" if {
	not input.provenance.exists
}

violations contains "SLSA Level 1: Build process is not scripted (manual build steps detected)" if {
	input.provenance.exists
	not input.build.scripted
}

violations contains sprintf("SLSA Level %d: Required minimum SLSA level not met (current: %d)", [required_slsa_level, current_slsa_level]) if {
	current_slsa_level < required_slsa_level
}

violations contains "SLSA Level 2: Provenance not generated by the build service itself" if {
	required_slsa_level >= 2
	not input.build.service_generated_provenance
}

violations contains "SLSA Level 2: Source code not in a version control system" if {
	required_slsa_level >= 2
	not input.source.version_controlled
}

violations contains "SLSA Level 3: Build platform is not hardened (shared/mutable environment)" if {
	required_slsa_level >= 3
	not input.build.hardened_platform
}

violations contains "SLSA Level 3: Build environment is not isolated (hermetic builds required)" if {
	required_slsa_level >= 3
	not input.build.isolated_environment
}

# =============================================================================
# ARTIFACT SIGNING (Sigstore / Cosign)
# =============================================================================

violations contains "Signing: Artifact is not signed (Cosign/Sigstore signature missing)" if {
	not input.artifact.signed
}

violations contains "Signing: Artifact signature verification failed" if {
	input.artifact.signed
	not input.artifact.signature_verified
}

violations contains "Signing: Signing identity not from an approved OIDC provider" if {
	input.artifact.signed
	input.artifact.signature_verified
	not approved_signing_identity(input.artifact.signing_identity)
}

approved_oidc_providers := {
	"https://token.actions.githubusercontent.com",
	"https://gitlab.com",
	"https://accounts.google.com",
}

approved_signing_identity(identity) if {
	some provider in approved_oidc_providers
	startswith(identity.issuer, provider)
}

# =============================================================================
# SBOM (Software Bill of Materials)
# =============================================================================

violations contains "SBOM: No SBOM attached to artifact (SPDX or CycloneDX required)" if {
	not input.sbom.present
}

violations contains "SBOM: SBOM format not recognized (expected SPDX-2.x or CycloneDX-1.x)" if {
	input.sbom.present
	not input.sbom.format in {"SPDX-2.2", "SPDX-2.3", "CycloneDX-1.4", "CycloneDX-1.5", "CycloneDX-1.6"}
}

violations contains "SBOM: SBOM contains no components (empty bill of materials)" if {
	input.sbom.present
	count(input.sbom.components) == 0
}

violations contains "SBOM: SBOM missing required field 'document_namespace'" if {
	input.sbom.present
	not input.sbom.document_namespace
}

violations contains "SBOM: SBOM missing required field 'creation_timestamp'" if {
	input.sbom.present
	not input.sbom.creation_timestamp
}

violations contains "SBOM: SBOM components are missing PURL (Package URL) identifiers" if {
	input.sbom.present
	some component in input.sbom.components
	not component.purl
}

violations contains "SBOM: SBOM components missing license declarations" if {
	input.sbom.present
	some component in input.sbom.components
	not component.license_declared
	not component.license_concluded
}

# =============================================================================
# DEPENDENCY HYGIENE
# =============================================================================

violations contains sprintf("Dependencies: Floating version constraint '%s' found in %s (pin to exact version)", [dep.version, dep.name]) if {
	some dep in input.dependencies
	is_floating_version(dep.version)
}

is_floating_version(version) if { version == "latest" }
is_floating_version(version) if { version == "*" }
is_floating_version(version) if { version == "" }
is_floating_version(version) if { startswith(version, "^") }
is_floating_version(version) if { startswith(version, "~") }
is_floating_version(version) if { startswith(version, ">") }
is_floating_version(version) if { contains(version, "x") }

violations contains sprintf("Dependencies: %s@%s has known CVE %s (CVSS %.1f — %s)", [dep.name, dep.version, vuln.cve_id, vuln.cvss_score, vuln.severity]) if {
	some dep in input.dependencies
	some vuln in dep.vulnerabilities
	vuln.cvss_score >= 7.0
	not vuln.exempted
}

violations contains sprintf("Dependencies: %s@%s has critical CVE %s with no exemption", [dep.name, dep.version, vuln.cve_id]) if {
	some dep in input.dependencies
	some vuln in dep.vulnerabilities
	vuln.severity == "critical"
	not vuln.exemption_approved
}

# =============================================================================
# LICENSE COMPLIANCE
# =============================================================================

# Copyleft licenses that require special handling in commercial products
strong_copyleft_licenses := {
	"GPL-2.0", "GPL-2.0-only", "GPL-2.0-or-later",
	"GPL-3.0", "GPL-3.0-only", "GPL-3.0-or-later",
	"AGPL-3.0", "AGPL-3.0-only", "AGPL-3.0-or-later",
	"SSPL-1.0",
}

violations contains sprintf("License: %s uses %s (strong copyleft — legal review required for commercial distribution)", [dep.name, dep.license]) if {
	input.policy.enforce_license_compliance
	some dep in input.sbom.components
	dep.license_concluded in strong_copyleft_licenses
	not dep.license_exemption_approved
}

violations contains sprintf("License: %s has no license declaration (unknown license risk)", [dep.name]) if {
	input.policy.enforce_license_compliance
	some dep in input.sbom.components
	not dep.license_concluded
	not dep.license_declared
}

# =============================================================================
# BUILD PROVENANCE INTEGRITY
# =============================================================================

violations contains "Provenance: Build source URI does not match expected repository" if {
	input.provenance.exists
	input.provenance.build_definition.external_parameters.source_uri
	not startswith(
		input.provenance.build_definition.external_parameters.source_uri,
		input.policy.expected_source_uri_prefix,
	)
}

violations contains "Provenance: Build triggered from unprotected ref (branch builds not allowed for releases)" if {
	input.provenance.exists
	input.artifact.is_release
	input.provenance.build_definition.external_parameters.ref_type == "branch"
}

violations contains "Provenance: Provenance predicate type not SLSA v1.0" if {
	input.provenance.exists
	input.provenance.predicate_type != "https://slsa.dev/provenance/v1"
}

violations contains "Provenance: Builder identity not in approved builder registry" if {
	input.provenance.exists
	not approved_builder(input.provenance.run_details.builder.id)
}

approved_builders := {
	"https://github.com/actions/runner",
	"https://github.com/slsa-framework/slsa-github-generator",
	"https://cloudbuild.googleapis.com/GoogleHostedWorker",
	"https://gitlab.com/gitlab-org/gitlab-runner",
}

approved_builder(builder_id) if {
	some approved in approved_builders
	startswith(builder_id, approved)
}

# =============================================================================
# COMPLIANCE REPORT
# =============================================================================

slsa_assessment := {
	"compliant":           compliant,
	"slsa_level_achieved": current_slsa_level,
	"slsa_level_required": required_slsa_level,
	"slsa_level_met":      current_slsa_level >= required_slsa_level,
	"artifact_signed":     object.get(input, ["artifact", "signed"], false),
	"sbom_present":        object.get(input, ["sbom", "present"], false),
	"violation_count":     count(violations),
	"violations":          [v | some v in violations],
}

compliance_report := {
	"framework":    "SLSA v1.0 + Supply Chain Governance",
	"standard":     "supply_chain.slsa",
	"compliant":    compliant,
	"assessment":   slsa_assessment,
	"controls_checked": {
		"provenance":   true,
		"signing":      true,
		"sbom":         true,
		"dependencies": true,
		"licenses":     object.get(input, ["policy", "enforce_license_compliance"], false),
	},
}
